### ISSUE TITLE
Concurrent write command problem

### ISSUE THREAD

**Issue by racletteparty** [gce-electronics/HA_RFPlayer#103]
### System Health details

OK

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When multiple RF Player commands are sent at the same time we get an exception from the serial driver

### Reproduction steps

1. Create an automation that sends a RF Player command (e.g. switch on) for multiple entities at the same time
2. From time to time you will get an Error logs from the serial driver

### Debug logs

```text
Error doing job: Exception in callback SerialTransport._write_ready() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/serial_asyncio/__init__.py", line 268, in _write_ready
    assert self._flushed()
           ^^^^^^^^^^^^^^^
AssertionError
```

**Comment by racletteparty** [comment]
Commands are not anymore sent in separate thread from the executor but rather in the main async loop.
