### ISSUE TITLE
Issue with 2025.1 and pydantic upgrade

### ISSUE THREAD

**Issue by Aohzan** [gce-electronics/HA_RFPlayer#112]
### System Health details

-

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

pydantic_core._pydantic_core.ValidationError: 687 validation errors for list[RfpDeviceProfile]

See https://developers.home-assistant.io/blog/2024/12/21/moving-to-pydantic-v2/

### Reproduction steps

1. 2025.1 ugprade (only beta for now)

### Debug logs

```text
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rfplayer/__init__.py", line 28, in async_setup_entry
    await gateway.async_setup()
  File "/config/custom_components/rfplayer/gateway.py", line 80, in async_setup
    self.profile_registry = await async_get_profile_registry(self.hass, self.verbose)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rfplayer/device_profiles.py", line 362, in async_get_profile_registry
    return await hass.async_add_executor_job(_get_profile_registry, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/rfplayer/device_profiles.py", line 357, in _get_profile_registry
    return ProfileRegistry(module_path / "device-profiles.yaml", verbose)
  File "/config/custom_components/rfplayer/device_profiles.py", line 251, in __init__
    self.register_profiles(f.read())
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/config/custom_components/rfplayer/device_profiles.py", line 257, in register_profiles
    items = parse_obj_as(list[RfpDeviceProfile], obj)
  File "/usr/local/lib/python3.13/site-packages/pydantic/deprecated/tools.py", line 42, in parse_obj_as
    return TypeAdapter(type_).validate_python(obj)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/pydantic/type_adapter.py", line 412, in validate_python
    return self.validator.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        object,
        ^^^^^^^
    ...<3 lines>...
        allow_partial=experimental_allow_partial,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
pydantic_core._pydantic_core.ValidationError: 687 validation errors for list[RfpDeviceProfile]
0.match.sub_type
  Field required [type=missing, input_value={'protocol': 'X10|DOMIA', 'info_type': '0'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.match.id_phy
  Field required [type=missing, input_value={'protocol': 'X10|DOMIA', 'info_type': '0'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.platforms.binary_sensor.0.device_class
  Field required [type=missing, input_value={'name': 'On/Off', 'state....infos.subTypeMeaning'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.platforms.binary_sensor.0.category
  Field required [type=missing, input_value={'name': 'On/Off', 'state....infos.subTypeMeaning'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.platforms.binary_sensor.0.unit
  Field required [type=missing, input_value={'name': 'On/Off', 'state....infos.subTypeMeaning'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.platforms.binary_sensor.0.state.bit_mask
  Field required [type=missing, input_value={'value_path': '$.frame.infos.subTypeMeaning'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.platforms.binary_sensor.0.state.bit_offset
  Field required [type=missing, input_value={'value_path': '$.frame.infos.subTypeMeaning'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.platforms.binary_sensor.0.state.map
  Field required [type=missing, input_value={'value_path': '$.frame.infos.subTypeMeaning'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.platforms.binary_sensor.0.state.factor
  Field required [type=missing, input_value={'value_path': '$.frame.infos.subTypeMeaning'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.platforms.binary_sensor.0.state.unit_path
  Field required [type=missing, input_value={'value_path': '$.frame.infos.subTypeMeaning'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.platforms.binary_sensor.0.state_class
  Field required [type=missing, input_value={'name': 'On/Off', 'state....infos.subTypeMeaning'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.platforms.climate
  Field required [type=missing, input_value={'binary_sensor': [{'name...rame.header.rfLevel'}}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.platforms.cover
  Field required [type=missing, input_value={'binary_sensor': [{'name...rame.header.rfLevel'}}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.platforms.light
  Field required [type=missing, input_value={'binary_sensor': [{'name...rame.header.rfLevel'}}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.platforms.sensor.0.category
  Field required [type=missing, input_value={'name': 'Rf Level', 'dev....frame.header.rfLevel'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
0.platforms.sensor.0.state.bit_mask
  Field required [type=missing, input_value={'value_path': '$.frame.header.rfLevel'},
```

**Comment by Aohzan** [comment]
fixed in https://github.com/gce-electronics/HA_RFPlayer/pull/114
